server:
  port: 8989
spring:
  application:
    name: GATEWAY
  config:
    import: configserver:http://localhost:9196
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      routes:
        - id: order-service #give any name
          uri: lb://order-service #should start with lb following service name. lb denoting load balancer.
          predicates:
          - Path=/order/**
        - id: payment-service
          uri: lb://payment-service 
          predicates:
          - Path=/payment/**
          

